// PM2 Ecosystem Configuration — 3-Instance Load Balanced
// 使用方法: pm2 start ecosystem.config.js
module.exports = {
  apps: [
    {
      name: 'yunwei-1',
      script: 'server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '2G',
      kill_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        PORT: '8765',
        TZ: 'Asia/Shanghai',
        DB_HOST: '127.0.0.1',
        DB_PORT: '3306',
        DB_USER: 'root',
        DB_PASSWORD: 'Wh111852',
        DB_NAME: 'gms',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT: '6379',
      },
      error_file: '/tmp/yunwei-1-error.log',
      out_file: '/tmp/yunwei-1-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'yunwei-2',
      script: 'server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '2G',
      kill_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        PORT: '8766',
        TZ: 'Asia/Shanghai',
        DB_HOST: '127.0.0.1',
        DB_PORT: '3306',
        DB_USER: 'root',
        DB_PASSWORD: 'Wh111852',
        DB_NAME: 'gms',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT: '6379',
      },
      error_file: '/tmp/yunwei-2-error.log',
      out_file: '/tmp/yunwei-2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'yunwei-3',
      script: 'server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '2G',
      kill_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        PORT: '8767',
        TZ: 'Asia/Shanghai',
        DB_HOST: '127.0.0.1',
        DB_PORT: '3306',
        DB_USER: 'root',
        DB_PASSWORD: 'Wh111852',
        DB_NAME: 'gms',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT: '6379',
      },
      error_file: '/tmp/yunwei-3-error.log',
      out_file: '/tmp/yunwei-3-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
