services:
  - type: web
    name: gms-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: TZ
        value: Asia/Shanghai
